- util/epoll/epoll_proactor_test.cc
- util/epoll/proactor.cc
- util/fiber_sched_algo.cc
- util/uring/proactor.cc
The issue is about main io loop blocking on epoll_wait when in fact there are active fibers that could be running. It's either dispatch fiber that has not run yet or user fibers that were activated but the state machine has not took it into the account. Now I wrote enough comments that hopefully further refactorings won't introduce this bug again. In addition, I added the test to epoll_proactor_test that reproduced the bug with some probability.
> Fix deadlock bug in epoll proactor.

- blaze.sh
Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
When compiling I encountered the following problem：
It is because the lower version of cmake does not support -B. So add a version determination for cmake in blaze.sh. Now when a low version of cmake is encountered there is the following output：
This is a very common situation, many people have both cmake and cmake3 on their machines.
> fix: Unfriendly output in blaze.sh for cmake versions below 3.4

- util/dns_resolve.cc
Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
I encountered the following problem when compiling：
__sigval_t has limitations, to take two different examples：
Linux VM-9-54-centos 5.4.119-1-tlinux4-0008 #1 SMP Fri Nov 26 11:17:45 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux VM-16-16-ubuntu 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
This change was made for better compatibility.
> fix: __sigval_t causes compile error.

- cmake/third_party.cmake
- patches/mimalloc-v2.0.5.patch
This PR is for enabling memory defragmentation using mimalloc
There are two issue that this should solve:
1. We are building mimalloc as release version, but DF can then build as debug, this create different structs sizes between mimallc and DF (because of different flags that the header files and source files "see").
2. Adding a function that checks whether a given page is underutilised.
3. the third party cmake will apply the patch as part of the build.
Signed-off-by: Boaz Sade <boaz@dragonflydb.io>
> mimalloc patching for memory defrag

- .github/workflows/ci.yml
- examples/CMakeLists.txt
- examples/https_client_cli.cc
- util/http/http_client.cc
- util/http/http_client.h
- util/tls/tls_socket.cc
- util/tls/tls_socket.h
This add support for HTTPS client.
The code is based on the existing HTTP client and the TLS socket. What it adds is:
* HTTPS client that uses the TLS socket under the hood.
* A demo application that can be use to demo this new client.
note that the application is very useful to ensure that the TLS is working successfully.
I tried to make sure that this will be as secure as possible without making the use of it to complicated (i.e. loading cert file for example).
Signed-off-by: Boaz Sade <boaz@dragonflydb.io>
> support for https added as well as an example application

- cmake/third_party.cmake
- patches/mimalloc-v2.0.7.patch
This PR do not include any code changes, but it does update the mimallc version from 2.0.5 to 2.0.7
This include also applying a new patch that add a function that would enable trekking page memory utilisation as well as to ensure that while we're compiling this lib once, it would have the same structures sizes for both building externally in debug and release mode.
Signed-off-by: Boaz Sade <boaz@dragonflydb.io>
> mi malloc update to version 2.0.7

- base/CMakeLists.txt
- base/io_buf.cc
- base/io_buf.h
- io/io.cc
- io/io.h
- io/io_test.cc
Some things that I desperately missed in DF:
- IoBuf is not movable (And is wrapped often into unique_ptr to account for this 🤯 )
- IoBuf WriteAndCommit akin to ReadAndConsume
- IoBuf cannot be used as a sink or as a source
- There is no way to convert Bytes into string_view easily
> Cleanup IoBuf and add source/sink for it

- base/varz_node.cc
- util/fiber_socket_base.h
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/fiber2_test.cc
- util/fibers/fiberqueue_threadpool.cc
- util/fibers/proactor_base.h
- util/fibers/synchronization.h
- util/fibers/uring_proactor.cc
- util/uring/proactor.cc
- util/varz.h
Parking lot is a global table that allows parking fibers without maintaining dedicated spinlocks and waiting queues. The parking-lot framework maintains a resizeable hashtable that uses spinlocks per bucket. When a hashtable needs resizing it's done in such way that fibers do not need to contend on bucket array pointer. bucket array replacement is performed using qsbr technique together with derred deletions.
> Introduce faber native parking-lot ability.

- io/proc_reader.cc
- io/proc_reader.h
Save SWAP information from `/proc/meminfo`, can also be used in determining whether the SWAP file is enabled or not.
> Save SWAP information from `/proc/meminfo`

- util/CMakeLists.txt
- util/cloud/CMakeLists.txt
- remove the override of OPENSSL_ROOT_DIR
- allow to pass a custom OpenSSL folder from build command as -DOPENSSL_ROOT_DIR=/path/to/openssl/folder
- make sure crypto and ssl library using the same installation source
> allow to compile with an OpenSSL installation

- util/http/http_common.cc
- util/http/http_common.h
- util/http/http_handler.cc
- util/http/profilez_handler.cc
Allow only paths starting with `/tmp/profile`
> Don't allow arbitrary paths in /filez endpoint

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/scheduler.cc
- util/fibers/fiber2_test.cc
- util/fibers/synchronization.cc
- util/fibers/synchronization.h
Specifically, move ActivateOther under lock because in case a remote fiber times out, its liveness is not guaranteed outside of the lock.
> Fix ownership issues when notifying fibers

- cmake/internal.cmake
Example: `cxx_test(subdir/some_test.cc ...)`
> feat(cmake): Allow specifying tests in a subdir

- cmake/internal.cmake
This PR comes after the compilation of adding s390x arch support in dragonflydb.
> feat(cmake): Adapt compile flags for s390x arch

- util/tls/tls_socket.cc
- util/tls/tls_socket.h
This is used such that connections can be downgraded from tls to non-tls
> feat(tls-socket): allow tls socket to cache the first bytes received

- util/fibers/CMakeLists.txt
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/fiber_interface_impl.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/detail/wait_queue.cc
- util/fibers/detail/wait_queue.h
- util/fibers/epoll_proactor.cc
- util/fibers/fibers_test.cc
- util/fibers/synchronization.cc
- util/fibers/synchronization.h
- util/fibers/uring_proactor.cc
The fix addresses #92 
Specifically, it introduces a dedicated WaitQueue and Waiter objects that allow registering into a wait list before suspending. 
Now, `FiberInterface::wait_link` was removed and fibers register via  intrusive `Waiter` object on stack. 
Moreover, the old approach of preventing the double booking int remote ready queue was removed and now we prevent double booking by unloading remote-ready queue in case the active fiber was added to it.
I also introduced an epoch-based notification mechanism, but I am not sure it's needed so I added `LOG(FATAL)` check to test it. We should notify exactly once based on the WaitQueue and we should not have dangling notifications, therefore I expect we won't have late notifications now.
> Remove spurious wakeup notifications

- base/CMakeLists.txt
- util/fibers/CMakeLists.txt
> fix: move rt library dependency to fibers2 lib

- examples/echo_server.cc
- examples/pingserver/ping_iouring_server.cc
- util/accept_server.h
- util/connection.h
- util/fiber_socket_base.h
- util/fibers/accept_server.cc
- util/fibers/fiber_socket_test.cc
- util/fibers/listener_interface.cc
- util/fibers/proactor_base.h
- util/http/http_client.cc
- util/http/http_client.h
- util/listener_interface.h
- util/tls/tls_engine_test.cc
- util/tls/tls_socket.cc
- util/tls/tls_socket.h
TlsSocket is constructed by a pointer to the next socket, effectively acting as a decorator/proxy object of the underline socket. This however is problematic, because once a connection upgrades to tls, you now need to keep alive two different objects with whose lifetime semantics are bound. Therefore, we make TlsSocket own the underline socket, to avoid decoupling the lifetime of the two sockets.
> feat(TlsSocket): add ownership semantics to TlsSocket

- base/pmr/arena.h
- base/pmr/memory_resource.h
- base/pmr/pod_array.h
- util/http/http_main.cc
- util/proactor_pool.h
We did some recent changes I think, so now we have errors - https://github.com/dragonflydb/dragonfly/actions/runs/5601507387/jobs/10245489679?pr=1525#step:7:1297.
I can compile dragonfly locally with Clang after this change.
> Cleanup the <memory_resource> include mess.

- util/fiber_socket_base.h
- util/fibers/epoll_socket.cc
- util/fibers/fiber_socket_base.cc
Running locally found `EpollSocket::Accept` was just blocking forever and never suspending the fiber - looks like `FD_CLOEXEC` is being set with `F_SETFL` instead of `F_SETFD` which is then breaking `O_NONBLOCK`
@romange this is part of the cause of the deadlock you mentioned (if `Accept` never releases the fiber the accept loop never finishes so `AcceptServer::Stop` blocks in the test tear down) - though theres then another issue where `shutdown` isn't waking up the `accept` fiber so it still blocks `Stop` (will look at that separately)
> fix: fix non-linux set nonblocking

- util/accept_server_test.cc
- util/fibers/epoll_socket.cc
- util/uring/uring_socket.cc
Fixes running the accept server tests with `epoll` (setting `USE_URING` to false). Before the socket was being closed by the wrong thread so hitting the `EpollProactor::Disarm` assertion (https://github.com/romange/helio/blob/0ec06cf8277ebb2e976afdda4f7304fc64010884/util/fibers/epoll_proactor.cc#L372)
Or is epoll meant to support closing from a different thread?
(Note `kqueue` still blocks on tear down due to the `shutdown` not waking the accept fiber issue)
> fix: fix accept server test with epoll

- util/fibers/epoll_socket.cc
- util/fibers/epoll_socket.h
As mentioned in https://github.com/romange/helio/pull/111, `shutdown` doesn't seem to wake up the socket accept fiber (can't find any reference to this but running locally getting the same behaviour, wheras `epoll` is woken)
With this the accept server tests pass ok as the accept fiber no longer blocks on tear down (theres some other failures on MacOS but they seem unrelatex)
This seemed simpler than using `EVFILT_USER` since AFAICT the trigger must include the `centries_` index, which the socket doesn't know, and it requires calling back to the proactor, which notifies the kqueue, which calls `Wakey`, so seemed easier just to call directly? It is still a bit hacky - the `#ifndef __linux__` is probably redundant but figured better to include to be safe
> fix: wake kqueue socket on shutdown

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/scheduler.cc
- util/fibers/epoll_socket.cc
- util/fibers/fibers_test.cc
Fixes [dragonflydb/dragonfly/1591](https://github.com/dragonflydb/dragonfly/issues/1591)
The problem is that a code path in `EpollSocket::RecvMsg` would not reset `read_context_` so fibers would resume at random suspend points outside.
> Fix bug in EpollSocket::RecvMsg

- util/fibers/listener_interface.cc
I was trying to be clever by including the number of threads in the estimation, turns out this is annoying because `pool_` can be null.
This time at I also have the Dragonfly side already done with tests so we don't have to do any more ping-pong :)
> Remove usage of pool_ for threads estimate as it can be uninitialized.

- base/CMakeLists.txt
- base/ring_buffer.h
- base/ring_buffer_test.cc
1. Add testing coverage and a bunch of `[D]CHECK`s
2. Slightly improve (IMO) the exposed functions. In particular, the new `GetTail` allows optional overriding which will allow reusing resources without having to construct a new intermediate object.
Part of the road towards partial sync :)
> ring_buffer: Add tests coverage and clean-up the interface a bit.

- util/http/http_handler.cc
- util/http/http_handler.h
- util/http/http_main.cc
We should probably protect the metrics page somehow, this is the quickest way to do it.
This is currently untested because testing is kind of a hassle (no http unit tests at all currently). However I tested it works locally and I'm willing to write a Python test with `requests` once it's merged :)
> feat(http): Add authentication support

- base/mpsc_intrusive_queue.h
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/wait_queue.cc
- util/fibers/detail/wait_queue.h
- util/fibers/fibers_test.cc
- util/fibers/synchronization.cc
- util/fibers/synchronization.h
Specifically, fix #130.
The code that crashed makes sure that a fiber is not in remote_ready queue when it wakes up: it yields if it is, and thus allows the dispatcher to empty the remote queue and pull the active fiber from there.
The code crashes because after the Yield call, it appears that the fiber is still in the remote queue. Based on the code inspection, it seems unprobable that a dispatcher won't empty the remote queue, therefore I suspect that remote queue was corrupted in the first place.
This fix focuses on ScheduleFromRemote (producer sider) that before that did not protect against concurrent calls for the same fiber. It was partly justified because ScheduleFromRemote is usually called from the WaitQueue code under lock. However, there are other cases that can call this …
> An attempt fixing the bug with inconsistent state in fibers

- util/cloud/aws.cc
- util/cloud/s3.cc
- util/cloud/s3.h
Fixes https://github.com/dragonflydb/controlplane/issues/225, where if the bucket or key includes a character that AWS expects to be URL encoded, the signature will be invalid
AWS defines their own URL path encoding in https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html:
```
URI encode every byte. UriEncode() must enforce the following rules:
- URI encode every byte except the unreserved characters: 'A'-'Z', 'a'-'z', '0'-'9', '-', '.', '_', and '~'.
- The space character is a reserved character and must be encoded as "%20" (and not as "+").
- Each URI encoded byte is formed by a '%' and the two-digit hexadecimal value of the byte.
- Letters in the hexadecimal value must be uppercase, for example "%1A".
- Encode the forward slash character, '/', everywhere except …
```
> fix(s3): fix url encoding s3 path

- util/cloud/aws.h
- util/cloud/s3.cc
- util/cloud/s3_file.cc
- util/cloud/s3_file.h
When opening a read file, pass ownership of the HTTP client to the read file - this matches the behaviour of `OpenWriteFile`
Can refactor more later to make this a bit cleaner, though adding for now to get loading snapshots from S3 working (otherwise the bucket must not be destructed before the file which is messy to implement when the 'S3' file is used as a generic interface)
> feat(s3): pass ownership of http client to s3 read file

- .github/workflows/ci.yml
- util/http/http_client.cc
- util/tls/tls_engine.cc
- util/tls/tls_engine.h
Use SSL_CTX_set_default_verify_paths as a fallback. The motivation is that when we statically link openssl, it tries to load certificates from the folder that existed on the build distribution and it fails loading certificates on the target platform.
> Prefer hard-coded ssl certificates location first

- CMakeLists.txt
Newer CMakes start giving this error - "Compatibility with CMake < 3.5 will be removed from a future version of CMake."
3.16 is the version installed on Ubuntu 20.04
> Bump CMakeLists.txt minimum version

- util/fibers/epoll_proactor.cc
The `read` call at https://github.com/romange/helio/blob/4c261c19f415ffde5ec9af09915d4d3704e330fe/util/fibers/epoll_proactor.cc#L465 blocks forever meaning that thread is just blocked. That `read` makes sense with Linux `timerfd_create` though I don't understand it for `kqueue`
> fix: macos thread blocking in `EpollProactor::PeriodicCb`

- cmake/third_party.cmake
- examples/CMakeLists.txt
- examples/s3v2_demo.cc
- patches/aws-sdk-cpp-3e51fa016655eeb6b6610bdf8fe7cf33ebbf3e00.patch
- util/aws/CMakeLists.txt
- util/aws/aws.cc
- util/aws/credentials_provider_chain.cc
- util/aws/credentials_provider_chain.h
- util/aws/http_client.cc
- util/aws/http_client.h
- util/aws/http_client_factory.cc
- util/aws/http_client_factory.h
- util/aws/logger.cc
- util/aws/logger.h
- util/aws/s3_endpoint_provider.cc
- util/aws/s3_endpoint_provider.h
- util/aws/s3_read_file.cc
- util/aws/s3_read_file.h
- util/aws/s3_write_file.cc
- util/aws/s3_write_file.h
Adds support for using the AWS SDK.
Using the AWS SDK isn't ideal as it doesn't work that well with fibers and is slow and complex to build given it has lots of dependencies, though it seems like the simplest and fastest way to build a reliable S3 client for snapshots. Long term we may want to copy the subset of the SDK we use and re-implement, though that would still be a lot of work given theres a lot of complexity and edge cases...
Adds a custom AWS logger that uses glog, rather than the default AWS logger which writes to a file so requires separate configuration
This has some duplication, though I'm not sure how to avoid that. Since we're using glog, if the log is disabled the right side of the log won't run, including `message_stream.str()` which does a copy, so if we refactored that …
> feat(aws): add aws sdk support

- util/aws/s3_write_file.cc
- util/aws/s3_write_file.h
Using the CRC32 header works on MinIO, though running again on S3 before merging the dragonfly changes found S3 returning:
```
Checksum Type mismatch occurred, expected checksum Type: null, actual checksum Type: crc32
```
I don't understand why given it has headers:
```
x-amz-sdk-checksum-algorithm: CRC32\r\n
x-amz-checksum-crc32: uDr/9A==\r\n
```
So I don't know why it expects no checksum... I'm fairly certain it worked before, though maybe I was only testing MinIO (another argument for regression tests using S3 directly)
Will remove for now just to unblock merging the Dragonfly side (it was to improve resource usage rather than a functional requirement) - will look at next
> feat(aws): remove crc32 checksum

- util/tls/tls_engine.cc
see https://github.com/dragonflydb/dragonfly/actions/runs/6436749970/job/17480707509?pr=1998#step:10:1424
We peek into tls engine to see if it produced some output to write into a socket, then we write some and then we consume (drain) the output that we written. The flow is not atomic so it may definitely create errors but unfortunately I still do not understand context well enough to fix the code.
> fix: expand on a check-fail output that crashed in a test

- examples/s3_demo.cc
- util/aws/http_client.cc
- util/aws/http_client.h
- util/aws/s3_endpoint_provider.cc
- util/aws/s3_endpoint_provider.h
- util/http/http_client.cc
Adds HTTPS support to the AWS S3 client. (Will also add a dragonfly option to disable/enable HTTPS)
This uses the existing TLS client context and setup (since the AWS HTTP client writes directly to the socket, using `TlsClient` itself would be a pain so it just copies what it needs).
Since the HTTPS client is shared by multiple proactors, this still doesn't do connection caching. This has a bigger overhead with HTTPS than HTTP though is still negligible compared to the 8MB chunk uploads and downloads so I don't think thats an issue (users can disable HTTPS for S3 endpoints if preferred).
(Will add connection caching if/when replacing the AWS SDK and add a separate HTTP client per proactor rather than a global shared client)
**TLS**
Not all AWS endpoints support TLS 1.3, though all support …
> feat(aws): add https support

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/fiber_interface_impl.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/epoll_proactor.cc
- util/fibers/fiber2.h
- util/fibers/uring_proactor.cc
This metric should help us measuring responsiveness of fiber switching.
> chore: track delays when context switching between fibers

- util/fibers/listener_interface.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/listener_interface.h
Specifically, during the function stack migration between threads we may encounter faulty compiler optimizations in the release mode. See https://stackoverflow.com/questions/75592038/how-to-disable-clang-expression-elimination-for-thread-local-variable for more details.
> fix: prevent compiler optimizations related to loading stale tls object

- examples/raw_echo_server.cc
- util/fibers/CMakeLists.txt
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/detail/utils.cc
- util/fibers/detail/utils.h
- util/fibers/epoll_proactor.cc
- util/fibers/fiber2.h
- util/fibers/uring_proactor.cc
Replace fiber switch latency measurement with cycle clock, assuming that modern CPUs have constant tsc cycle and these measurements are not critical for correctness.
> fix: improve time measurement performance in fibers

- examples/echo_server.cc
- util/connection.h
- util/fibers/epoll_proactor.cc
- util/fibers/epoll_proactor.h
- util/fibers/fiber_socket_test.cc
- util/fibers/fibers_test.cc
- util/fibers/listener_interface.cc
- util/fibers/pool.cc
- util/fibers/proactor_base.h
- util/fibers/proactor_pool.cc
- util/fibers/sliding_counter.cc
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/varz.cc
- util/metrics/metrics.cc
1. The failure in `TLConnList::List` has been reproduced on aarch64 due to `ProactorBase::me()` call that was substituted by the compiler with the wrong instance. The irony that we use this call to check our invariants.
2. I redesigned the access to ProactorBase::GetIndex and made it accessible from any thread.
3. Removed `DEBUG_proactor` data member and use `socket()->proactor()` instead.
4. Removed the fallback for unlinking in a differrent thread and introduced back the check-fail
> fix: errorneus check-fail due to redundant tls read

- cmake/third_party.cmake
Required to build on ubuntu 23.10 and later
> fix: update gperftools version and tune its configure flags

- .github/workflows/ci.yml
- cmake/third_party.cmake
- util/accept_server_test.cc
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/epoll_proactor.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
- util/fibers/uring_socket.h
Before, we used a temporary fiber to pass along the migrated fiber to another proactor. Now, we simplify the transition by using the dispatcher fiber that also handles I/O loop. We switch to it and execute the delegation to another proactor.
Also, remove the old code and get rid of sccache that is not very reliable.
> chore: reimplement fiber migrate

- util/accept_server_test.cc
- util/fibers/accept_server.cc
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/fiber_socket_base.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
The main change is that we now rely on liburing function io_uring_peek_batch_cqe
to peek for completions instead of manually iterating with `io_uring_for_each_cqe` call.
The reason for this is that iouring API evolved, and the logic for peeking completions became
non-trivial: it requires calling a system call in some rare cases. So
in terms correctness and ease of maintainance it's better to rely on the library function to do the right job.
In addition, fibers scheduler code has non-functional changes:
a. Added a trace variable to ease with debugging: it shows the last transitioned state of the fiber
in ambigous situations.
b. ProcessSleep now returns the number of woken fibers.
> chore: general improvements to fibers

- examples/echo_server.cc
- util/accept_server_test.cc
- util/fiber_socket_base.h
- util/fibers/detail/scheduler.cc
- util/fibers/fiber_socket_base.cc
- util/fibers/listener_interface.cc
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
- util/fibers/uring_socket.h
1. Fixed socket migration code.
2. Enabled direct-fd feature for server side sockets for kernels that support it.
3. Added some stats about cqe completions to uring_proactor.
4. Added `maxclients` flag to echo_server. 
memtier load: `memtier_benchmark -s 172.31.36.182 --command=PING -t 16 -c 18 -n 60000 --hide-histogram --distinct-client-seed`
```
==================================================================================================
Type         Ops/sec    Avg. Latency     p50 Latency     p99 Latency   p99.9 Latency       KB/sec
--------------------------------------------------------------------------------------------------
Pings      968745.62         0.30147         0.30300         0.43900         0.51900     19866.85
```
``` …
```
> feat: enable direct-fd sockets

- examples/echo_server.cc
- examples/pingserver/ping_iouring_server.cc
- util/fibers/submit_entry.h
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
These provided buffer rings can be used by kernel for multishot operations to read the data directly into these buffers. No functionality changes yet, a test will be followed up with socket changes.
Also did some code clean ups on a way with echo server and ping_iouring_server (no functionality changes).
> feat: Add preliminary support to provided buffer rings

- util/fibers/uring_socket.cc
- util/fibers/uring_socket.h
Late event completions arrive even after CancelOnErrorCb was called. This PR fixes this by introducing a refcounted auxillary record that handles the state for completions even if socket was destroyed.
> fix: late event completions should not call user callbacks

- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/internal.cmake
- cmake/third_party.cmake
- util/fibers/epoll_proactor.cc
- util/fibers/epoll_proactor.h
- util/fibers/fiber_socket_test.cc
- util/fibers/fibers_test.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
1. Fix cmake flags so that we could run with sanitizers.
Note: due to fibers the address sanitizers is practically useless but
we will fix it in subsequent PRs.
The problem was that we need to compile abseil lib with the same debug flags like helio
so I moved those settings to before we include third_party libs.
2. Fix periodic timer cancelation on macos.
In general with epoll/kevent we can assume (for now) all the completions stop syncrhonously
Once we cancel/delete the timer so we can just explicitly delete "item" in epoll_proactor.
For io_uring the cancelation causes callback to run one more time so it will delete its item.
3. The rest is minor built/test fixes in fibers_test related to macos.
> enable macos ci

- base/io_buf.cc
The problem is that in `IoBuf::Reserve` method we allocate with:
```
uint8_t* nb = new (std::align_val_t{alignment_}) uint8_t[sz];
and later
delete[] buf_;
```
which causes an alignment mismatch
> fix(io_buf): new/delete alignment missmatch

- base/mpsc_intrusive_queue.h
- cmake/third_party.cmake
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
1.  `readelf --debug-dump=info ./echo_server | grep "DW_AT_producer"` shows that helio is compiled  with stack protection flags on my laptop,  even in O2 mode. Seems like some distro tweaking of gcc because I have not seen it before. As a result, when CPU profiling is enabled, dragonfly can crash with a message "stack smashing detected" . The stacktrace shows the failure happens inside `CpuProfiler::prof_handler` which is a signal handler of gperftools. Seems like a bad interaction of signal handling and stack protection code. Therefore, I disabled these stack flags for thirdpary libraries.
2. Unrelated, I added more logs inside fiber code for a check-fail that sometimes happens in dragonfly unit tests like this one: https://github.com/dragonflydb/dragonfly/actions/runs/7862807475/job/2145 …
> fix: disable stack protector that does not work well with gperftools

- base/mpsc_intrusive_queue.h
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/fiber_interface_impl.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/synchronization.cc
- util/fibers/synchronization.h
Before, we could get "no element" response, when in fact the queue is not empty. This can happen when `tail_` is being in the middle of the update but its "next" field has not been updated yet (inside Push).
Before the change, we treated this state as "Empty", while the queue could have multiple entries (probably 1 or 2). After this change: we retry the pop operation in scheduler until we reach the true depletion of the remote queue.
> fix: mpsc intrusive queue now reports its precise state during Pop

- .devcontainer/alpine/devcontainer.json
- .devcontainer/fedora/devcontainer.json
- .devcontainer/ubuntu22/devcontainer.json
- .devcontainer/ubuntu24/devcontainer.json
- .devcontainer/ubuntu24/post-create.sh
- .github/workflows/ci.yml
- CMakeLists.txt
- cmake/third_party.cmake
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/fiber_interface_impl.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/fibers_test.cc
1. Added devcontainer with ubuntu24/gcc13
2. Configured with using a custom boost library that uses ucontext implementation with asan enabled.
3. Fixed fibers code to support ucontext (we never supported yet and always used boost fcontext implementation)
4. Made sure that fibers_test pass under ASAN - fixed the leakage bug when accepting a socket.
> chore: Add support for ubuntu24 image

- .github/workflows/ci.yml
- cmake/third_party.cmake
- util/fibers/synchronization.h
1. Fix linker dependencies for cares on Apple.
2. Fix a memory order bug in event count during fastpath wait.
> chore: cares built on macos

- util/accept_server.h
- util/fibers/accept_server.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/fibers_test.cc
- util/fibers/listener_interface.cc
- util/listener_interface.h
- util/tls/tls_engine_test.cc
By default we preserve the current behavior and fallback with a memory resource that allocates using std::malloc/std::free.
Also, provide an example of how to customize memory functions for OpenSSL.
> chore: allow injection of memory_resource into accept server

- .github/workflows/ci.yml
- base/malloc_test.cc
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/fiber2.h
- util/fibers/fibers.cc
- util/fibers/submit_entry.h
- util/http/http_main.cc
Also add a microbenchmark measuring mmap and madvise calls.
a single madvise call takes around 100ns while mmap is x3 more expensive.
> chore: add IORING_OP_MADVISE support to iouring

- util/fibers/synchronization.cc
- util/fibers/synchronization.h
Forgot to add this one 😅 Need it for DCHECKs. DEBUG prefix is used mainly in DF to indicate it's better not used in real code
> chore: add DEBUG_Count() to barrier

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/fiber2.h
- util/fibers/fibers_test.cc
I used the following script to track RSS usage vs VM usage for fibers:
https://github.com/ARM-software/CSAL/blob/master/coresight-tools/cskern/pagemap.py
> chore: introduce worker fiber stack size tracking

- util/fibers/epoll_socket.cc
- util/fibers/listener_interface.cc
- util/tls/tls_socket.cc
- util/tls/tls_socket.h
1. Fixes https://github.com/dragonflydb/dragonfly/issues/2736
2. Make sure we call `Shutdown` when a connection is being closed.
3. Fix tls logic - if we have SSL errors, to continue writing the outgoing ssl stream to the underlying ssl socket
> chore: tls cleanups + remove spurious socket error

- util/fibers/listener_interface.cc
This happens in Dragonfly if we kill the server immediately after starting replication.
Fixes https://github.com/dragonflydb/dragonfly/issues/2737
> fix: Do not crash if connection is not found in list

- util/fibers/dns_resolve.cc
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/http/http_client.cc
- util/http/http_client.h
1. Prevent from FiberCall to wake up before its waker actually has been called.
2. Fix DnsResolve code to prevent notifying the wrong FiberCall on epoll event.
> fix: fibers/socket bugs

- util/connection.h
- util/fibers/listener_interface.cc
- util/tls/tls_engine.cc
- util/tls/tls_socket.cc
- util/tls/tls_socket.h
The root cause was due to a socket being closed and destroyed inside ListenerInterface::RunSingleConnection
and in parallel the listener was performing the shutdown sequence inside ListenerInterface::RunAcceptLoop().
In fact we had a comment saying it's working because socket.Shutdown did not preempt.
In one of my recent PRs I implemented the logic where TlsSocket informs the peer about the shutdown
which made the call preemptible. As a result the whole management code around this became unsafe.
1. I introduced an intrusive refcnt so that a connection would not be destroyed inside RunSingleConnection
when RunAcceptLoop still uses it.
2. Changed the iteration loop in the latter tu support preemption.
3. Fixed the Shutdown code to support the case where the tcp socket is closed in the …
> chore: Fix the crash in tls shutdown

- util/fibers/accept_server.cc
- util/fibers/listener_interface.cc
- util/fibers/uring_socket.cc
- util/listener_interface.h
There are two ways to stop accepting:
1. stop pulling a connection from the accept queue. This leads to a back pressure on a client side
2. Pull and immediately close. This usually leads to retries on the client side
This PR implements the second option, which seems like a bad idea, but in some cases is necessary. For example, when we failover to a differrent host, we want a client to retry until its DNS cache is updated with the new host ip and it reconnects to a differrent node. This mode essentially simulates the behavior of a closed port.
> feat: allow a listener to stop accepting new connections

- util/fibers/fibers_test.cc
- util/fibers/future.h
Introduce simple future to replace boost code
replacing aligned_storage with optional, intrusive_ptr with shared_ptr and a mutex with event-count makes the code ten times smaller 🙂
> chore: Simpler Future<> without locking

- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/synchronization.h
In order to progress around ProcessRemoteReady added epoch counter to show how far events are between pushing the fiber to the queue and trying to pull it.
> chore: add more logs around ProcessRemoteReady

- CMakeLists.txt
- base/CMakeLists.txt
- base/init.cc
- base/logging.cc
- base/logging.h
- cmake/third_party.cmake
- examples/echo_server.cc
- util/fibers/listener_interface.cc
- util/fibers/uring_socket.cc
- util/http/http_handler.cc
- util/http/profilez_handler.cc
Keep the default with the old glog library. The absl log library is missing a LOT of features, like logging into files, file rotation etc. Basically it provides only the low-level api to serialize log messes into sink and a stderr sink. This is not enough for prod use. Still, this PR provides a common ground to use both libraries in neutral way. If I have bandwidth I will fill in the functionality inside helio to be able to get rid of old glog
> chore: partial support of absl::log library

- CMakeLists.txt
- base/logging.cc
- cmake/third_party.cmake
The problem was the visibility of option `LEGACY_GLOG` which was not available when `included` the thirdparty cmake.
> fix visibility of LEGACY_GLOG in cmake/third_party

- base/cpu_features.cc
Fails to build on arm see https://github.com/dragonflydb/dragonfly/actions/runs/9743732272/job/26889678052#step:5:499
> fix: compile on arm missing bracket on cpu_features

- examples/gcs_demo.cc
- util/cloud/gcp/CMakeLists.txt
- util/cloud/gcp/gcs.cc
- util/cloud/gcp/gcs.h
- util/http/http_client.h
In addition, implement basic ListBuckets method for GCS.
> chore: Implement dev-credential support for GCS

- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/fibers.h
- util/fibers/fibers_test.cc
This can be used to debug deadlock states when the state is kept within the fiber stack.
> chore: add ability to print custom data during PrintAllFiberStackTraces

- util/accept_server_test.cc
- util/fibers/detail/wait_queue.h
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/synchronization.h
- util/fibers/uring_proactor.cc
Before we used a counter which allowed inner loops to shortcut and rarely reach ProcessSleepFibers call in high I/O situations.
Now, we also call ProcessSleepFibers when we process I/O completions that provides a good balance between responsiveness and the maintenance cost of checking for starvation.
Before I could observe delays reaching 2seconds between Heartbeat runs that where scheduled to run every 10ms (on highly loaded server in debug mode).
After: the delays have not crossed 40ms under the same conditions.
> fix: a better fix to sleeping fibers starvation

- CMakeLists.txt
- util/fibers/synchronization.h
`std::lock_guard` and `std::unique_lock` do not work with `ABSL_GUARD_XXX` variants and for that we need our own wrappers. Furthermore, even if helio doesn't use those guards right now, they might be useful in the future so I add them here and enable `-Wthread-safety` for clang
* enable -Wthread-safety
* add LockGuard as replacement of std::LockGuard
> chore: enable -Wthread-safety and add LockGuard

- util/fibers/detail/scheduler.cc
- util/fibers/epoll_proactor.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
Bundle DestroyTerminated together with ProcessSleep and run both of them periodically with predictable frequency but not too frequent.
> fix: run DestroyTerminated periodically without starvation

- util/fibers/detail/scheduler.cc
Before, we reset kScheduleRemote bit right after we pushed into the remote queue.
But if this thread is slow, it is possible that the notified fiber will wake up before we reset the bit,
and then it will go sleeping again and then another notifier will try to awake it and will check fail at line
scheduler.cc:238 when it checks that the bit is set.
If we reset it upon waking up, the fiber will reset it before suspending, so this situation can not happen.
In addition, we print the stacktrace when we reach unexpected state.
> fix: reset kScheduleRemote when we pull the queue

- util/fibers/synchronization.cc
- util/fibers/synchronization.h
cond_.notify_all() accesses unprotected wait_queue, therefore it must be under lock.
The problem was found in https://github.com/dragonflydb/dragonfly/actions/runs/11343555702/job/31546353995?pr=3924#step:12:818
> fix: data race for for Barrier::Wait()

- util/fiber_socket_base.h
- util/fibers/fiber_socket_test.cc
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
- util/fibers/uring_socket.h
Allows setting up multishot receive with provided buffers using io_uring sockets.
> chore: Introduce multishot-recv functionality.

- base/mpsc_intrusive_queue.h
- base/mpsc_intrusive_queue_test.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
The scenario is around remote fiber activation. And it goes like this:
1. A fiber is blocked on EventCount.wait_until (i.e. timed wait)
2. The fiber times outs but in parallel another thread sends it a notification via the remote queue.
3. EventCount::wait_until tries to pull itself from the remote queue, but does not find itself there, even though the notification was pushed STRICTLY BEFORE `active->PullMyselfFromRemoteReadyQueue()` call. We know it because the notify call is under the EventCount spinlock, and PullMyselfFromRemoteReadyQueue is done after the spinlock was grabbed and released.
The scenario happens when, the remote queue is empty but then something else tries to notify another, unrelated fiber in the thread, but does not finish crossing the blocking point (*). Then our …
> fix: provide a more precise detection of empty state in MPSCIntrusiveQueue

- util/fibers/accept_server.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
1. Relax ClearSignal function - now it can be called on unregistered signals (before it check-failed)
2. Now it is possible to install the ignore handler,
which is what we really want to use when we clear the signal handlers via AcceptServer.
Indeed, if accept server is shut down, the process will usually exit right after.
There will be some clean up code but that's it. So we do not want to interrupt due sigterm/sigint signals because
we are already in the process of shutting down anyway. Before this change - if we got the signal during the
critical section after the accept server handlers were cleared, and default handlers were installed,
the process would exit with -15 for SIGTERM and -2 for SIGINT just because it would catch these signals
during the shutdown.
> chore: improve signal handling code

- util/tls/tls_engine.cc
- util/tls/tls_engine.h
- util/tls/tls_engine_test.cc
- util/tls/tls_socket.cc
- util/tls/tls_socket.h
Allow cleaner separation between writing to ssl and flushing the ssl output buffer into a socket.
> chore: reimplement TlsSocket::WriteSome

- util/fibers/fiber_socket_test.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
- util/fibers/uring_socket.h
Given its restrictive api, where we need to allocate a buffer group per socket, I doubt it will be useful any time soon. Also, it's not supported on 6.8.
> feat: add SendProvided call

- util/fibers/epoll_socket.cc
- util/fibers/fiber_socket_test.cc
`sendmsg` returns the bytes written and `-1` if it failed. For the later, we need to poll ERNO, and for `EAGAIN` we need to block and retry later when we get notified. What this means is that the calling fiber must block on EAGAIN when we call WriteSome. However this is not the case as we improperly check: `if (res != EAGAIN)` which can't be true because we are on the path of `sendmsg` that returned `< 0`. We should check `ERRNO` and not `res`.
> fix: EpollSocket::WriteSome early return on EAGAIN

- util/fibers/proactor_pool.cc
Expression of the form `int arr[SOME_NON_CONSTANT]` are illegal by the C++ standard yet compilers support it as an extension. Let's not use that and use `vector` instead. On the bonus side we also now don't have a warning.
> fix: non constant expression in array size

- base/sse2neon.h
The files is taken from https://github.com/DLTcollab/sse2neon and it uses the MIT license.
> chore: update sse2neon.h to 01/2025 version

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/fibers.h
During debugging, it is sometimes useful to check how much stack space is left before calling a method. To do this, we can use `GetStackMargin`.
> feat(fibers): Add GetStackMargin method

- util/fibers/epoll_socket.cc
- util/fibers/epoll_socket.h
Fixes the problem described in https://github.com/dragonflydb/dragonfly/issues/4498 and here https://github.com/dragonflydb/dragonfly/issues/4498#issuecomment-2609240866
* fix async chaining
* small refactor
> fix: epoll socket async chaining and refactor

- util/cloud/gcp/gcs.cc
- util/cloud/gcp/gcs_file.cc
1. Invalid release up of the pool client handle.
2. add a missing header for gcp metadata request.
> chore: gcp code bugs

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/uring_socket.cc
Also, add a timestamp tracking when a fiber becomes suspended. This is handy when we print stacktraces.
> chore: more debug assertions coverage

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/fibers.h
To improve efficiency of fiber context switch operations.
> chore: more efficient access to FiberInterface epoch field

- util/fibers/synchronization.cc
- util/fibers/synchronization.h
If for some reasone a fiber was resumed not via wait_list_, we identify this and print the error message. We also attempt to do the self-healing fix by unlinking the waiter manually.
> chore: add debug printing for the Unlink bug

- util/accept_server_test.cc
- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/fiber_socket_test.cc
- util/fibers/fibers.h
- util/fibers/fibers_test.cc
- util/tls/tls_socket_test.cc
Also, perform some clean-up in the code i touched. FiberPriority is not used yet, it is only stored in FiberInterface. The only functional change is that it fibers use boost fixedsize_stack, we now pass the stack size through the Opts struct, which is 64KB, while default boost fixedsize_stack size was 128KB, hence the change in fibers_test.cc.
First step for #399
> feat: introduce FiberPriority

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface_impl.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/epoll_proactor.cc
- util/fibers/fibers_test.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
1. Move scheduling step into Scheduler::RunWorkerFibersStep from Epoll/Uring proactors.
2. Extend ProactorBase::Await to support Fiber::Opts
> chore: refactor scheduling code

- util/cloud/azure/azure.cc
- util/cloud/azure/creds_provider.h
- util/cloud/azure/storage.cc
- util/cloud/azure/storage.h
- util/cloud/gcp/gcp_creds_provider.h
- util/cloud/gcp/gcp_utils.cc
- util/cloud/gcp/gcp_utils.h
- util/cloud/gcp/gcs.cc
- util/cloud/gcp/gcs_file.cc
- util/cloud/utils.h
Small refactoring around cloud::CredentialsProvider so now Azure can rely on an abstract interface instead of using the concrete one.
> chore: refactor azure/gcp code

- util/fibers/detail/scheduler.cc
- util/fibers/proactor_base.cc
- util/fibers/proactor_base.h
- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
Beforehand we had a flag that was common to all proactors. Now the responsibility to override goes to caller and each proactor can have its own setting.
> chore: busy polling specific per proactor

- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
- util/fibers/uring_socket.cc
1. Optionally flush sqs on writes if the pending sq count is higher than the threshold.
2. Optionally flush sqs when waking up another thread.
3. Allow switching from msgring to event_fd wake configurations programatically.
> chore: more customizations of iouring behavior

- cmake/third_party.cmake
Problem:
With Boost 1.89+, BoostConfig no longer provides boost_systemConfig.cmake, so find_package(Boost CONFIG REQUIRED COMPONENTS system) fails.
Fixes: https://github.com/dragonflydb/dragonfly/actions/runs/17061127671/job/48370365579
> fix(cmake): add boost >= 1.89 compatibility for boost::system

- util/fibers/uring_proactor.cc
- util/fibers/uring_proactor.h
This is needed to prevent the situation when we enable msgring on platforms that do not support this API. See https://github.com/dragonflydb/dragonfly/issues/5693 for more context.
> fix: separate msgring support and enable states

- util/fibers/detail/fiber_interface.cc
- util/fibers/detail/fiber_interface.h
- util/fibers/detail/scheduler.cc
- util/fibers/detail/scheduler.h
- util/fibers/fibers_test.cc
High priority share the NORMAL queue with NORMAL fibers.
If a high priority fiber is activated, it is pushed to the front of the queue. If it yields, however, it is still pushed to back.
Also added support for priorities for default, main thread that does not run an I/O polling loop. It is mainly added for being able to test fibers without proactors.
> chore: add high priority to the scheduler
