romange/helio

util/fibers/event_count.h

for the compilation issue of dragonfly discussed at
https://github.com/dragonflydb/dragonfly/issues/248

fixing compatibility issue with boost-fiber 1.75

---

util/fibers/fibers_ext.h

Signed-off-by: Braydn <braydn.moore@uwaterloo.ca>

Added WaitFor as a public function to the Done class

---

examples/s3_demo.cc
util/cloud/CMakeLists.txt
util/cloud/aws.cc
util/cloud/aws.h

feat(util): Support multiple AWS key sources

---

examples/s3_demo.cc
util/cloud/CMakeLists.txt
util/cloud/s3.cc
util/cloud/s3.h
util/http/CMakeLists.txt
util/http/encoding.cc
util/http/encoding.h

Signed-off-by: Vladislav Oleshko <vlad@dragonflydb.io>
Fixes #12

feat(util): Support pagination in AWS ListObjects

---

examples/s3_demo.cc
util/cloud/aws.cc
util/cloud/aws.h
util/cloud/s3.cc
util/cloud/s3.h

Didn't test it yet on real EC2 (only on metadata mock), waiting for my token to expire 👀 
Fixes #15

feat(aws): Refresh expired session tokens

---

README.md

Signed-off-by: Junwang Zhao <zhjwpku@gmail.com>

[typo] io_ring->io_uring

---

util/proactor_base.cc
util/proactor_base.h
util/uring/proactor.cc

Improve OnIdleTasks management

---

io/io.cc
io/io.h

Signed-off-by: adi_holden <adi@dragonflydb.io>

io source: add string view source

---

examples/fiber.cc
examples/fiber.h
examples/fiber_test.cc
examples/raw_echo_server.cc
util/epoll/epoll_proactor_test.cc
util/fibers/fiber.h
util/fibers/fibers_ext_test.cc
util/proactor_base.cc
util/proactor_base.h
util/proactor_pool.h
util/tls/tls_engine_test.cc
util/uring/proactor_test.cc
util/uring/uring_socket_test.cc

Also add a PoC of fiber library in the examples folder.

Add fibers_ext::Fiber class that wraps boost fibers.

---

io/file.cc

Signed-off-by: adi_holden <adi@dragonflydb.io>

bug(file read): ReadAllPosix check vector len before access

---

util/fibers/fibers_ext.cc
util/fibers/fibers_ext.h
util/fibers/fibers_ext_test.cc

Signed-off-by: adi_holden <adi@dragonflydb.io>

feat(fibers ext): add barrier class with cancel call

---

util/fibers/fibers_ext.h

Signed-off-by: adi_holden <adi@dragonflydb.io>

feat(blocking counter): notify all on dec and cancel

---

examples/CMakeLists.txt
examples/fiber.cc
examples/fiber.h
examples/raw_echo_server.cc

Add multi-threading to raw_echo_server.

---

util/fibers/CMakeLists.txt
util/fibers/detail/fiber_interface.h
util/fibers/detail/result_mover.h
util/fibers/detail/scheduler.cc
util/fibers/detail/scheduler.h
util/fibers/event_count2.h
util/fibers/fiber2_test.cc
util/fibers/fiberqueue_threadpool.h
util/fibers/fibers_ext.h
util/fibers/proactor_base.cc
util/fibers/proactor_base.h
util/fibers/uring_proactor.cc
util/fibers/uring_proactor.h
util/uring/submit_entry.h

The new uring proactor does not require a separate scheduling algorithm - since this is now part of the main dispatch loop.

Introduce Uring proactor for fibers2

---

util/fibers/detail/fiber_interface.h
util/fibers/detail/scheduler.cc
util/fibers/fiber2_test.cc
util/fibers/proactor_base.h
util/fibers/synchronization.h
util/fibers/uring_proactor.cc

especially with EventCount when running fiber2_test.
fixes #49

Disable ParkingLot since it actually increases contention

---

cmake/third_party.cmake
examples/echo_server.cc
util/CMakeLists.txt
util/dns_resolve.cc

This PR is related to dragonfly's issue: https://github.com/dragonflydb/dragonfly/issues/947

Use c-ares to resolve DNS requests.

---

util/accept_server.cc
util/uring/uring_socket.cc

For dragonflydb/dragonfly/issues/931

feat: Support IPv6 addresses

---

base/init.cc

Found out that we miss the exception message while looking at the crash that resulted in dragonflydb/dragonfly/pull/1169.

Print exception.what() in the terminate handler when possible

---

base/expected.hpp

I had a few problems with clangd support, seems to have been fixed upstream.

chore: Update expected.hpp

---

util/fibers/dns_resolve.cc

This attempts to fix https://github.com/dragonflydb/dragonfly/issues/1486

fix(dns): Support multiple sockets in parallel

---

cmake/third_party.cmake

Fixes https://github.com/dragonflydb/dragonfly/issues/1504
Tested on a Fedora VM, and also locally with Ubuntu to make sure nothing breaks

Fix build issue on Fedora

---

base/abseil_test.cc
base/proc_util.cc
base/proc_util.h

Also, add parse HugetlbPages field.

chore: rewrite process status parsing code

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml

To avoid unformatted changes ;) 
1. Adds clang-format on pre-commit
2. Adds conventional commits

feat: add pre-commit on repo

---

util/tls/tls_socket.cc
util/tls/tls_socket.h

Close #105.
I hope my changes to the write loop are correct - please take a more deep look at them.

Improve TLS handling.

---

util/accept_server_test.cc
util/fibers/listener_interface.cc
util/fibers/proactor_pool.cc
util/listener_interface.h

For dragonflydb/dragonfly/issues/1496
cc @ashotland

feat(listener): Add a way to specify maximum number of connections

---

util/fibers/epoll_proactor.cc
util/fibers/proactor_base.cc
util/fibers/proactor_base.h
util/fibers/uring_proactor.cc

Addresses https://github.com/dragonflydb/dragonfly/issues/1705

fix: correctly handle cpu cycle reset events

---

util/fibers/CMakeLists.txt
util/fibers/detail/fiber_interface.cc
util/fibers/detail/fiber_interface.h
util/fibers/detail/scheduler.cc
util/fibers/detail/scheduler.h
util/fibers/fibers_test.cc
util/fibers/stacktrace.cc
util/fibers/stacktrace.h

I've been wanting something like this for a while.

feat(fibers): Add utility for dumping the stacktraces of all fibers in a thread

---

util/fibers/epoll_proactor.cc
util/fibers/epoll_proactor.h
util/fibers/fibers_test.cc
util/fibers/proactor_base.h

Add freebsd implementation as well.

chore: add periodic task test coverage

---

.github/workflows/ci.yml
util/fiber_socket_base.h
util/fibers/epoll_socket.cc
util/fibers/epoll_socket.h
util/fibers/fiber_socket_test.cc
util/fibers/uring_socket.cc
util/fibers/uring_socket.h
util/tls/tls_socket.cc
util/tls/tls_socket.h

There's a minimal Dragonfly PR ready as well.

feat(sock): Add a new cancellation callback interface.

---

util/http/http_handler.cc
util/http/http_handler.h
util/http/http_main.cc

* This PR allows the user of `HttpListenerBase` to register a `cb` that if it returns true, it will skip the `auth`.
* Added `username_` field to `HttpListenerBase` such that we can verify against a specific username
@romange I decided to slightly diverge from what we originally discussed, namely that the customization point will be the `auth` callback. For our use case, we don't really need that, as the only thing we want to do, is to skip the `auth` part on certain `paths`. Otherwise, we would need to also expose to the user, functions that deal with parsing of the `http` protocol and for our use case this is not really needed.

feat(HttpHandler): allow to skip auth on paths via callback

---

base/init.cc

chore: allow optionally initializing glog lib 

---

util/fibers/epoll_proactor.cc

Fixes https://github.com/dragonflydb/dragonfly/issues/2014

fix: round the timeout up instead of rounding it down

---

util/fiber_socket_base.h
util/fibers/epoll_socket.cc
util/fibers/fiber_socket_base.cc
util/fibers/fiber_socket_test.cc
util/fibers/uring_socket.cc

Andy if you read this, please be wary of rebasing onto this once merged because it'll break Dragonfly
Needed for https://github.com/dragonflydb/dragonfly/pull/2033

fix: pass uds socket flag to peers

---

README.md

fixed typos and grammatical mistakes for better readability

fix: typos and grammatical mistakes in README.md

---

util/aws/credentials_provider_chain.cc

Add web identity credential provider to chain (needed for k8s integration)

feat(aws): add web identity provider

---

util/fibers/simple_channel.h

This type of channel is very similar to `SimpleChannel`, but it also tracks the size of `T`s it owns.

Add `SizeTrackingChannel`

---

util/accept_server_test.cc
util/connection.h
util/fibers/detail/fiber_interface.h
util/fibers/detail/scheduler.h
util/fibers/listener_interface.cc
util/listener_interface.h

Also, provide additional debugging variable inside connection to allow tracking of its thread assignment.

fix: optimize intrusive types

---

util/fibers/fiber_socket_test.cc
util/fibers/uring_socket.cc

Also make sure we cover all the error codepaths for during RegisterOnErrorCb/CancelOnErrorCb flows.

chore: add a unit test covering CancelOnErrorCb

---

base/mpmc_bounded_queue.h
util/fibers/accept_server.cc
util/fibers/detail/fiber_interface.cc
util/fibers/detail/scheduler.cc
util/fibers/epoll_proactor.cc
util/fibers/fibers_test.cc
util/fibers/proactor_base.h
util/fibers/uring_proactor.cc

1. Fix debug crash when a machine suspends and tsc is reset.
2. Improve a fiber test
3. Fix warnings.

chore: fibers improvements

---

util/accept_server_test.cc
util/fiber_socket_base.h
util/fibers/accept_server.cc
util/fibers/epoll_proactor.cc
util/fibers/epoll_proactor.h
util/fibers/fiber_socket_base.cc
util/fibers/listener_interface.cc
util/fibers/proactor_base.h
util/fibers/submit_entry.h
util/fibers/uring_proactor.cc
util/fibers/uring_proactor.h
util/fibers/uring_socket.cc
util/fibers/uring_socket.h
util/tls/tls_socket.cc
util/tls/tls_socket.h

Also, harden socket-related interfaces.

chore: remove old and unused code

---

README.md

chore: add Boost.Fiber acknowledgements

---

util/fibers/uring_proactor.cc

1. Use io_uring_submit_and_get_events to both submit events and also fetch completions in single syscall.
2. Make the critical section around blocking I/O command `wait_for_cqe` as small as possible to increase the chances that another thread will notify the proactor in time. That should decrease the amount of false positives where proactor blocks and then immediately wakes up do to notifications via kernel.
3. Added an optimization flags for kernels >= 6.0.
Some naive tests showed 5-10% reduction in proactor polling counts.
I also compared this PR (with all the other changes in helio) vs dragonfly v1.13:
run: `memtier_benchmark -s 172.31.36.182 --command=PING -t 32 -c 10 -n 300000 --hide-histogram --distinct-client-seed` from a 32 cpu machine while running dragonfly on a 8-cpu server …

chore: improve uring performance

---

util/fibers/uring_file.cc

fix: pass offset -1 to allow atomic sequential writes

---

io/io.h
util/fibers/CMakeLists.txt
util/fibers/synchronization.h
util/fibers/uring_file.cc
util/fibers/uring_file.h
util/fibers/uring_file_test.cc

Also, kill virtual inheritance for LinuxFile and just make it concrete. Finally a trivial test is added for covering some of the uring_file code.

feat: introduce async interface for the LinuxFile

---

cmake/third_party.cmake
util/fibers/listener_interface.cc

Also, check socket on shutdown.

chore: avoid building tests and examples in uring project

---

CMakeLists.txt
util/fibers/detail/fiber_interface.h
util/fibers/fiber2.h
util/fibers/fibers_test.cc
util/fibers/listener_interface.cc
util/listener_interface.h

Change the default stack size for connection fibers from 132KB to 64KB

feat: allow fiber stack size customization

---

.github/workflows/ci.yml
base/malloc_test.cc
util/fibers/accept_server.cc
util/fibers/detail/fiber_interface.cc
util/fibers/detail/fiber_interface.h
util/fibers/detail/scheduler.cc
util/fibers/fiber2.h
util/fibers/fibers.cc
util/fibers/submit_entry.h
util/fibers/synchronization.cc
util/fibers/synchronization.h
util/http/http_main.cc
util/proactor_pool.h

* Splits BlockingCounter/Impl into BlockingCounter and EmbeddedBlockingCounter, so the latter can be re-used
* Adds DCHECKs
* Adds clear comments to headers

chore: Refactor BlockingCounter

---

util/fibers/listener_interface.cc
util/fibers/proactor_pool.cc
util/listener_interface.h
util/proactor_pool.h
util/sliding_counter.h

Fixes https://github.com/dragonflydb/dragonfly/issues/2820

fix: allow consistent traversals

---

util/fibers/submit_entry.h
util/fibers/uring_file.cc
util/fibers/uring_file.h
util/fibers/uring_file_test.cc
util/fibers/uring_proactor.cc
util/fibers/uring_socket.cc

Also fix a bug where we override kver.kernel inside uring proactor (affects kernels 5.x)

feat: LinuxFile supports direct fd descriptors

---

io/io.cc
util/tls/tls_socket.cc

* fixes the infinite loop cause by this corner case
I am also adding a test case in df repo for this :)

fix: infinite loop on tls sock when BIO is full and client renegotiates the handshake

---

.github/workflows/ci.yml
cmake/third_party.cmake

MacOs/gcc stopped working for some reason on github, so disabling it.
Also update benchmark to latest version.

fix: disable MacOs

---

util/accept_server_test.cc
util/fibers/uring_proactor.cc

Also, disable enable_direct_fd until we improve it.

chore: add a test for socket Shutdown/RegisterOnErrorCb

---

.github/workflows/ci.yml

Fix CI with new container settings.

chore: Fix CI with new container settings

---

.github/workflows/mac-os.yml
cmake/third_party.cmake
util/accept_server_test.cc

Update the runner to macos 13 following this issue https://github.com/actions/runner-images/issues/9997

chore: fix mac os ci

---

cmake/third_party.cmake

chore: update mimalloc to 2.1.6

---

examples/gcs_demo.cc
util/cloud/gcp/gcp_utils.cc
util/cloud/gcp/gcp_utils.h
util/cloud/gcp/gcs.cc
util/cloud/gcp/gcs.h
util/cloud/gcp/gcs_file.cc
util/http/http_client.h
util/http/https_client_pool.cc
util/http/https_client_pool.h

chore: refresh auth-token automatically

chore: support instance metadata

---

util/fibers/uring_proactor.cc

Before - when the CPU is very busy it could reach the point where it never processed sleeping fibers.
Now we reduce the probability of it happens by limiting the number of times we can shortcut the flow before reaching the ProcessSleepFibers function.

fix: avoid starvation of processing sleeping fibers

---

util/fibers/listener_interface.cc

Add more logs to figure out where we deadlock during shutdown in df

chore: add more vlog info in RunAcceptLoop

---

examples/echo_server.cc
util/fiber_socket_base.h
util/fibers/detail/fiber_interface.cc
util/fibers/epoll_socket.cc
util/fibers/epoll_socket.h
util/fibers/uring_proactor.cc
util/fibers/uring_proactor.h
util/fibers/uring_socket.cc
util/fibers/uring_socket.h
util/tls/tls_socket.cc
util/tls/tls_socket.h

Provide basis code for multishot support for socket receive operations together with provided buffers.

chore: iouring/multishot part 1

---

examples/gcs_demo.cc
util/cloud/azure/azure.cc
util/cloud/azure/creds_provider.h
util/http/http_common.cc
util/http/http_common.h
util/http/http_handler.cc
util/http/http_server_utils.h

chore: more work on glob list - Azure API

---

examples/gcs_demo.cc
util/cloud/azure/CMakeLists.txt
util/cloud/azure/azure.cc
util/cloud/azure/creds_provider.h
util/cloud/azure/storage.cc
util/cloud/azure/storage.h
util/cloud/gcp/gcp_creds_provider.h
util/cloud/gcp/gcp_utils.cc
util/cloud/gcp/gcs.cc
util/cloud/utils.cc
util/cloud/utils.h

Extract common code under cloud/utils.h

chore: refactor azure/gcp code

---

base/function2.hpp
base/mpmc_bounded_queue.h
cmake/third_party.cmake
examples/gcs_demo.cc
util/cloud/azure/storage.cc
util/cloud/azure/storage.h

Update function2.hpp
Refactor azure storage code.

chore: update test/benchmark libraries

---

util/fibers/CMakeLists.txt
util/fibers/detail/fiber_interface.cc
util/fibers/detail/fiber_interface.h
util/fibers/fibers_test.cc

this setting ensures healthy stack margins for fibers stacks.

chore add HELIO_STACK_CHECK setting

---

util/fibers/proactor_base.cc
util/fibers/proactor_base.h

1. Update comments
2. Improve garbage collection of removed tasks.

fix: OnIdleTask interface

---

util/fibers/detail/scheduler.cc

fix(scheduler): Remove redundant DCHECK in Scheduler

---

util/cloud/gcp/gcs.cc

ADC will now be retrieved as follows:
1. If `GOOGLE_APPLICATION_CREDENTIALS` exists, it will be used to determine the ADC file (new)
2. Otherwise, if ~/.config/gcloud exists, get the credentials from the active account.
3. Otherwise, fetch from metadata server
Fixes [dragonflydb/dragonfly/#4396](https://github.com/dragonflydb/dragonfly/issues/4396)

fix: make GCS authentication honor Application Default Credentials

---

examples/echo_server.cc
util/fiber_socket_base.h
util/fibers/epoll_socket.cc
util/fibers/uring_socket.cc

Fix echo_server with newer api

fix: echo_server works with multishot

---

examples/echo_server.cc
util/fiber_socket_base.h
util/fibers/fiber_socket_test.cc
util/fibers/uring_proactor.cc
util/fibers/uring_proactor.h
util/fibers/uring_socket.cc
util/fibers/uring_socket.h

Fix completion handling bugs with multishot.
Optimize access to buffer ids iteration for bundles.

chore: iouring/multishot improvements

---

util/fibers/synchronization.cc
util/fibers/synchronization.h

This reverts commit 23b1f5a4cf89e61cd7b04527afbd15e3f0f2a5b6.

Revert "chore: add debug printing for the Unlink bug (#390)"

---

util/fibers/listener_interface.cc

fix: change the log level for accept error

fix: change the log level for accept error

---

util/tls/tls_socket.cc
util/tls/tls_socket_test.cc

The bug is in TlsSocket::HandleUpstreamWrite and it went undetected
because it requires a mixture of interactions that are hard to achieve locally with regression tests.
This PR sinthesizes the same conditions of concurrent write and consume on TlsEngine that result in short write.

fix: short write in the tls socket

---

cmake/third_party.cmake
io/file_util.cc

1. Fix cmake warnings for newer cmake version (alpine)
2. Change StatFiles to use statx on linux. fixes #1

chore: minor fixes

---

.github/workflows/mac-os.yml
base/cycle_clock.h
base/init.cc
util/fibers/epoll_proactor.cc
util/fibers/proactor_base.cc
util/fibers/proactor_base.h
util/fibers/uring_proactor.cc

Factor out the implementation from proactor_base.h

chore: introduce CycleClock based on tsc

---

util/fibers/accept_server.cc
util/fibers/listener_interface.cc
util/listener_interface.h

Moved lambda to be a free function. Also moved listener breaking code into ListenerInterface class for better encapsulation.
No functional changes.

chore: refactor code in accept_server

---

util/fibers/future.h

This function is useful when debugging deadlocks.

chore: add Future::GetFor function

---

util/tls/tls_socket.cc
util/tls/tls_socket.h
util/tls/tls_socket_test.cc

* implement AsyncWriteSome in TlsSocket

chore: implement TlsSocket::AsyncWriteSome

---

util/tls/tls_socket.cc

Before:
We returned partial data even if more bytes were available in the TlsEngine. This is due to the fact that SSL_read can return short reads and our code should handle it appropriately.

fix: short reads in tls socket

---

util/fibers/detail/fiber_interface.cc
util/fibers/detail/fiber_interface.h
util/fibers/detail/fiber_interface_impl.h
util/fibers/detail/scheduler.cc
util/fibers/detail/scheduler.h
util/fibers/epoll_proactor.cc
util/fibers/fibers.h
util/fibers/fibers_test.cc
util/fibers/uring_proactor.cc

feat(scheduler): support scheduling of background fibers

---

util/fibers/detail/scheduler.cc
util/fibers/detail/scheduler.h

chore(scheduler): Make scheduler configurable

---

util/fibers/detail/scheduler.cc
util/fibers/detail/scheduler.h

Change background_sleep_freq to be %

---

.github/workflows/mac-os.yml
cmake/third_party.cmake
util/cloud/gcp/gcs.cc
util/cloud/gcp/gcs_file.cc
util/cloud/utils.cc
util/cloud/utils.h
util/fibers/fibers_test.cc

Also, handle gracious close of http connection on a storage server if it asks for it (reuse_connecton is false).

fix: mac-os build failures

---

util/fibers/submit_entry.h
util/fibers/uring_file.cc
util/fibers/uring_file.h
util/fibers/uring_file_test.cc

* add fsync in SubmitEntry
* add statx in SubmitEntry
* fix fallocate arguments in SubmitEntry
* add blocking fsync and statx to UringFiler

chore: add fsync and statx in SubmitEntry
